#中文分词测试
# 参考: https://github.com/medcl/elasticsearch-analysis-ik
#Analyzer: ik_smart , ik_max_word , Tokenizer: ik_smart , ik_max_word

GET http://node205:9200/_analyze
Content-Type: application/json

{
  "text": "中华人民共和国爱吃土豆","analyzer":"ik_smart"
}

###

PUT http://node205:9200/index

###

POST http://node205:9200/index/fulltext/1
Content-Type: application/json

{
  "content": "美国留给伊拉克的是个烂摊子吗"
}

###

POST http://node205:9200/index/fulltext/2
Content-Type: application/json

{
  "content": "公安部：各地校车将享最高路权"
}

###
POST http://node205:9200/index/fulltext/3
Content-Type: application/json

{
  "content": "中韩渔警冲突调查：韩警平均每天扣1艘中国渔船"
}

###
POST http://node205:9200/index/fulltext/4
Content-Type: application/json

{
  "content": "中国驻洛杉矶领事馆遭亚裔男子枪击 嫌犯已自首"
}

###


POST http://node205:9200/index/fulltext/_search
Content-Type: application/json

{
  "query": {
    "match": {
      "content": "中国"
    }
  },
  "highlight": {
    "pre_tags": [
      "<tag1>",
      "<tag2>"
    ],
    "post_tags": [
      "</tag1>",
      "</tag2>"
    ],
    "fields": {
      "content": {}
    }
  }
}


###
GET http://node205:9200/order_details/_mapping

###
